== Modellkatalog [[Modellkatalog]]

=== Hva bruker du en modellkatalog til?

Informasjonsmodeller fra en eller flere virksomheter samles i en modellkatalog. En modellkatalog kan ses som et omslag til eller innbinding av modellene. En modellkatalog skal ha én utgiver, og en og samme virksomhet kan være utgiver av flere modellkataloger.

===  Hvordan beskriver du en modellkatalog?

Som minimum skal følgende egenskaper ha verdier:

* beskrivelse (`dct:description`): En kort og presis beskrivelse av modellkatalogen skal gjøre det lett for andre å se hva det inneholder. Beskrivelse er et obligatorisk felt. Bør gjentas når beskrivelsen finnes i flere ulike språk/målformer.

*  identifikator (`dct:identifier`): Obligatorisk (se <<om-identifikator, Om ... «identifikator»>>).

*  tittel (`dct:title`): Kortfattet om katalogen. Angi, uten å liste, hvilke modeller den omfatter, f.eks. «Informasjonsmodellene til Digitaliseringsdirektoratet». Bør gjentas når tittelen finnes i flere ulike språk/målformer.

* modell (`modelldcatno:model`): Referanser til en eller flere informasjonsmodeller som er inkludert i modellkatalogen.

**  Kommentar: I https://data.norge.no/specification/modelldcat-ap-no/#Forenklet-modell[UML-diagrammet i ModellDCAT-AP-NO] står det at `dct:hasPart` er obligatorisk mens `modelldcatno:model` er anbefalt. `dcat:Resource` som `dct:hasPart` peker på er en abstrakt klasse og skal erstattes med instanser av subklassen `modelldcatno:InformationModel` eller `dcat:Catalog`. Bortsett fra tilfeller der man beskriver en modellkatalog bestående av andre modellkataloger, skal en modellkatalog ha minst én informasjonsmodell.

*  utgiver (`dct:publisher`): Se <<om-utgiver-og-produsent, Om ... «utgiver»>>.

=== Eksempel på en modellkatalog (i RDF Turtle)


Se https://github.com/Informasjonsforvaltning/modelldcat-ap-no/blob/develop/examples/testModCat1.ttl[eksemplet i RDF Turtle].

===  Hva gjør du når du skal publisere modellkatalogen din i Felles datakatalog?


Når du skal publisere katalogen din i Felles datakatalog, må modellene mappes iht. ModellDCAT-AP-NO til et format som kan høstes. Pr. i dag støtter Felles datakatalog følgende RDF-serialiseringer: RDF/XML, Turtle og JSON-LD.

Modellkatalogen må da legges ut som en nettressurs, f.eks. i Github. URIen til nettressursen registreres i Felles datakatalog, og katalogen høstes så automatisk.
