== Generelt [[Generelt]]



=== Om bruk av egenskap «identifikator» (`dct:identifier`) [[om-identifikator]]

Egenskapen `dct:identifier` brukes til å oppgi identifikatoren til subjektet (første leddet) i en RDF-trippel. Subjektet i en RDF-trippel er per definisjon en identifikator (URI). I en konkret realisering vil instanser av klassene (inkl. deres subklasser) Modellkatalog (`dcat:Catalog`), Informasjonsmodell (`modelldcatno:InformationModel`), Modellelement (`modellcatno:ModelElement`), Egenskap (`modelldcatno:Property`), Kodeliste (`modelldcatno:CodeListe`) og Kodeelement (`modelldcatno:CodeElement`) derfor få en «innebygd» identifikator. Det er med andre ord strengt tatt ikke nødvendig å ha en identifikator (`dct:identifier`) i tillegg til den «innebygde» identifikatoren.

Egenskapen `dct:identifier` er derfor satt som anbefalt og ikke obligatorisk i de nevnte klasser og deres subklasser, med unntak av for Modellkatalog (`dcat:Catalog`). `dct:identifier` er satt som obligatorisk for Modellkatalog (`dcat:Catalog`) for at ModellDCAT-AP-NO skal være kompatibel med DCAT-AP-NO, ettersom `dct:identifier` er obligatorisk for `dcat:Catalog` der.

Egenskapen `dct:identifier` trenger ikke å inneholde den samme identifikatoren som den innebygde URIen i en RDF-trippel, men når det er den samme identifikatoren, anbefales det at hele den innebygde URIen (subjektet i en trippel) kopieres til `dct:identifier` i en Modellkatalog (`dcat:Catalog`).

Eksempel i RDF Turtle:

----
@prefix dct:  <http://purl.org/dc/terms/> .
@prefix dcat: <http://www.w3.org/ns/dcat#> .
@prefix xsd:  <http://www.w3.org/2001/XMLSchema#> .

<https://examples.com/infomoc/exmodcat1> a dcat:Catalog ;
   dct:identifier "https://examples.com/infomod/exmodcat1"^^xsd:anyURI .
----

Identifikatoren bør utformes i henhold til https://www.digdir.no/digitale-felleslosninger/peikarar-til-offentlege-ressursar-pa-nett/1492[_Standard for pekere til offentlige ressurser på nett_].

=== Om bruk av egenskap «utgiver» (`dct:publisher`) og «produsent» (`dct:creator`) [[om-utgiver-og-produsent]]

Det anbefales å bruke følgende mønster for URI til utgiver (`dct:publisher`) og produsent (`dct:creator`), der det siste leddet er organisasjonsnummeret:
-----
<enInfoModell> dct:publisher <https://organization-catalogue.fellesdatakatalog.digdir.no/organizations/974760673> .
-----

Når det er behov for å oppgi at «eieren» for en informasjonsmodell som ikke er den samme som utgiveren (`dct:publisher`), anbefales det å bruke produsent (`dct:creator`).

=== Om bruk av egenskap «dekningsområde» (`dct:spatial`) [[om-dekningsområde]]

Til dekningsområde (`dct:spatial`), anbefales det å bruke EU sine kontrollerte vokabularer https://op.europa.eu/en/web/eu-vocabularies/dataset/-/resource?uri=http://publications.europa.eu/resource/dataset/continent[Continent], https://op.europa.eu/en/web/eu-vocabularies/dataset/-/resource?uri=http://publications.europa.eu/resource/dataset/country[Country],  og https://op.europa.eu/en/web/eu-vocabularies/dataset/-/resource?uri=http://publications.europa.eu/resource/dataset/place[Place]. Eksemplet under (i RDF Turtle) viser bruk av Country-vokabularet for å oppgi Norge (NOR):

-----
<enInfoModell> dct:spatial <http://publications.europa.eu/resource/authority/country/NOR> . # Norge
-----

Det anbefales å bruke Kartverket sine kontrollerte vokabularer for fylke  og kommune. Eksemplene under viser Oslo som fylke hhv. kommune.

----
<mod1> dct:spatial <https://data.geonorge.no/administrativeEnheter/fylke/id/173159> . # Oslo som fylke

<mod2> dct:spatial <https://data.geonorge.no/administrativeEnheter/kommune/id/173018> . # Oslo som kommune
----

Du kan finne fram til URIene https://data.geonorge.no/administrativeEnheter/nasjon/doc/173163[her].

===  Om bruk av egenskap «lisens» (`dct:license`) [[om-lisens]]

For lisens (`dct:license`) anbefales det å bruke EU sitt kontrollerte vokabular for lisens, https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/licence[Licence], hvis lisensen du bruker finnes på listen. I eksemplet under er det https://creativecommons.org/licenses/by/4.0/[CC BY v. 4.0] som er brukt.
-----
<enInfoModell> dct:license <http://publications.europa.eu/resource/authority/licence/CC_BY_4_0> .
-----
