name: build adocs v1 and publish to production (legacy)

permissions:
  contents: write

on:
  push:
    branches:
      - v1
    paths:
      - docs/**
  workflow_dispatch:

jobs:
  build-adocs:
    name: Build adocs and deploy to GitHub Pages
    if: github.event_name != 'workflow_dispatch' || github.ref == 'refs/heads/v1'
    uses: Informasjonsforvaltning/workflows/.github/workflows/specification-github-pages.yaml@main
    with:
      ref: v1
      program_html: |
        asciidoctor -D docs -o index.html -a lang=nb docs/main.adoc
      program_pdf: |
        asciidoctor-pdf -D docs -o files/veileder-modelldcat-ap-no.pdf -a lang=nb docs/main.adoc
      program_pdf_continue_on_error: true
      publish_branch: html
      publish_dir: ./docs
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
